/* AUTO-GENERATED by scripts/dev/gen-levels.cjs — do not hand-edit.
   Regenerate: node scripts/dev/gen-levels.cjs
   60 levels under the position-band law (tuning.json: A=1-10, B=11-30,
   C=31-60). All 10 greybox kit levels are kept (* in table): kit 1-4 open the
   game, kit 5-10 are redistributed into their lawful bands. The rest are
   generated per lanthorn-prd/01-level-design-spec.md. Every level validated
   by the greedy bot (100 seed-variants, no assist) against
   tuning.json bands; authored queues of generated levels are bot-winnable.
   Master seed 20260611.

lvl band arch    win%  bandMin  median  par  verdict   (* = greybox kit level)
  1  A   A*     100%     85%       7    5  PASS
  2  A   A*     100%     85%      12    6  PASS
  3  A   B*     100%     85%       8    4  PASS
  4  A   B*     100%     85%      14    7  PASS
  5  A   B      100%     85%      13    8  PASS
  6  A   C       99%     85%      16    7  PASS
  7  A   B      100%     85%      19    9  PASS
  8  A   D       98%     85%      19   10  PASS
  9  A   E       97%     85%      17   10  PASS
 10  A   A      100%     85%      10    6  PASS
 11  B   C      100%     70%      13    7  PASS
 12  B   B      100%     70%      16   10  PASS
 13  B   C*      99%     70%      14    8  PASS
 14  B   B       99%     70%      19   12  PASS
 15  B   E       98%     70%      11    4  PASS
 16  B   B       99%     70%      11    6  PASS
 17  B   C       98%     70%      19    9  PASS
 18  B   D       98%     70%      11    6  PASS
 19  B   E       98%     70%      14    8  PASS
 20  B   F       87%     70%      25   11  PASS
 21  B   C*      98%     70%      14    7  PASS
 22  B   D       97%     70%      16   10  PASS
 23  B   B       96%     70%      16   10  PASS
 24  B   D       96%     70%      21   13  PASS
 25  B   F       95%     70%      16    6  PASS
 26  B   D*      95%     70%      10    5  PASS
 27  B   C       91%     70%      19    7  PASS
 28  B   E       90%     70%      19   11  PASS
 29  B   F       89%     70%      10    5  PASS
 30  B   A      100%     70%      12    8  PASS
 31  C   D       96%     55%      16   10  PASS
 32  C   B       95%     55%      16    7  PASS
 33  C   D       95%     55%      12    7  PASS
 34  C   C       95%     55%      16    9  PASS
 35  C   D       95%     55%      17   10  PASS
 36  C   B       95%     55%      17   10  PASS
 37  C   C       94%     55%      19   10  PASS
 38  C   B       94%     55%      19   12  PASS
 39  C   C       94%     55%      17   10  PASS
 40  C   F       73%     55%      20   12  PASS
 41  C   E       92%     55%      14    7  PASS
 42  C   C       92%     55%      16    9  PASS
 43  C   B       92%     55%      19   11  PASS
 44  C   C       94%     55%      19   10  PASS
 45  C   D       92%     55%      16    8  PASS
 46  C   B       92%     55%      16    8  PASS
 47  C   D       91%     55%      19   11  PASS
 48  C   C       91%     55%      17   10  PASS
 49  C   F       91%     55%      15    8  PASS
 50  C   A       94%     55%      19   10  PASS
 51  C   E       90%     55%      11    5  PASS
 52  C   D*      89%     55%      13    7  PASS
 53  C   E       87%     55%      19   10  PASS
 54  C   E*      86%     55%      19   10  PASS
 55  C   F       82%     55%      16    8  PASS
 56  C   E       81%     55%      16    7  PASS
 57  C   F       76%     55%      22    9  PASS
 58  C   E       74%     55%      22   11  PASS
 59  C   F*      75%     55%      19   13  PASS
 60  C   F       71%     55%      13    7  PASS
ALL LEVELS WITHIN BANDS ✓
*/
(function (root) {
  "use strict";
  const LEVELS = [
  {"id":1,"band":"A","archetype":"A","blocked":[],"lanterns":[[3,3],[4,4]],"seed":11001,"par":5,"kit":true},
  {"id":2,"band":"A","archetype":"A","blocked":[],"lanterns":[[2,5],[5,2]],"seed":11002,"par":6,"kit":true},
  {"id":3,"band":"A","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[0,3],[7,4]],"seed":11003,"par":4,"kit":true},
  {"id":4,"band":"A","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[3,0],[3,7],[6,3]],"seed":11004,"par":7,"kit":true},
  {"id":5,"band":"A","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[7,5],[3,6],[0,1]],"seed":492982,"par":8},
  {"id":6,"band":"A","archetype":"C","blocked":[[0,3],[7,3],[0,4],[7,4],[0,5],[7,5]],"lanterns":[[2,0],[4,7],[0,7]],"seed":755883,"par":7},
  {"id":7,"band":"A","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[1,3],[0,1],[6,1],[4,4]],"seed":898580,"par":9},
  {"id":8,"band":"A","archetype":"D","blocked":[[5,4],[5,5],[5,6]],"lanterns":[[2,2],[1,5],[4,1]],"seed":755848,"par":10},
  {"id":9,"band":"A","archetype":"E","blocked":[[3,4],[3,5],[3,2],[4,2],[6,4],[6,5]],"lanterns":[[0,5],[5,0],[7,4],[1,3]],"seed":485072,"par":10},
  {"id":10,"band":"A","archetype":"A","blocked":[],"lanterns":[[6,6],[6,0],[3,6]],"seed":189898,"par":6},
  {"id":11,"band":"B","archetype":"C","blocked":[[2,0],[2,7],[3,0],[3,7],[4,0],[4,7]],"lanterns":[[4,2],[6,7],[2,1]],"seed":270143,"par":7},
  {"id":12,"band":"B","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[4,3],[5,1],[2,6],[3,1],[2,3]],"seed":20340,"par":10},
  {"id":13,"band":"B","archetype":"C","blocked":[[2,0],[3,0],[4,0],[5,0],[2,7],[3,7],[4,7],[5,7]],"lanterns":[[3,1],[4,6],[0,0],[7,7]],"seed":11007,"par":8,"kit":true},
  {"id":14,"band":"B","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[7,4],[4,2],[7,6],[3,5],[5,1]],"seed":622362,"par":12},
  {"id":15,"band":"B","archetype":"E","blocked":[[2,5],[3,5],[4,3],[5,3]],"lanterns":[[3,0],[6,0],[5,5]],"seed":569867,"par":4},
  {"id":16,"band":"B","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[4,0],[2,6],[6,7]],"seed":436681,"par":6},
  {"id":17,"band":"B","archetype":"C","blocked":[[0,2],[7,2],[0,3],[7,3],[0,4],[7,4]],"lanterns":[[0,5],[7,7],[5,3],[4,6]],"seed":194161,"par":9},
  {"id":18,"band":"B","archetype":"D","blocked":[[2,3],[3,3],[4,3],[5,3]],"lanterns":[[4,1],[7,2],[0,3],[4,6]],"seed":899161,"par":6},
  {"id":19,"band":"B","archetype":"E","blocked":[[5,4],[5,5],[1,6],[2,6]],"lanterns":[[7,3],[0,6],[1,5],[0,4]],"seed":857451,"par":8},
  {"id":20,"band":"B","archetype":"F","blocked":[[0,7],[1,6],[2,5],[3,4],[4,3]],"lanterns":[[2,1],[5,4],[3,6],[0,5],[7,1]],"seed":676169,"par":11},
  {"id":21,"band":"B","archetype":"C","blocked":[[0,2],[0,3],[0,4],[0,5],[7,2],[7,3],[7,4],[7,5]],"lanterns":[[0,1],[4,4],[7,6]],"seed":11005,"par":7,"kit":true},
  {"id":22,"band":"B","archetype":"D","blocked":[[4,2],[5,2],[6,2]],"lanterns":[[1,7],[5,3],[0,1]],"seed":740047,"par":10},
  {"id":23,"band":"B","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[1,2],[5,1],[2,4],[1,7]],"seed":552012,"par":10},
  {"id":24,"band":"B","archetype":"D","blocked":[[2,5],[3,5],[4,5]],"lanterns":[[0,4],[7,6],[3,2],[5,3],[6,1]],"seed":880292,"par":13},
  {"id":25,"band":"B","archetype":"F","blocked":[[2,5],[3,4],[4,3],[5,2],[6,1]],"lanterns":[[3,0],[1,6],[6,0],[1,3]],"seed":380662,"par":6},
  {"id":26,"band":"B","archetype":"D","blocked":[[4,2],[4,3],[4,4],[4,5]],"lanterns":[[4,0],[4,7],[1,1]],"seed":11006,"par":5,"kit":true},
  {"id":27,"band":"B","archetype":"C","blocked":[[0,2],[7,2],[0,3],[7,3],[0,4],[7,4],[0,5],[7,5]],"lanterns":[[3,3],[1,1],[4,1],[5,7],[5,3]],"seed":810287,"par":7},
  {"id":28,"band":"B","archetype":"E","blocked":[[3,1],[3,2],[3,5],[3,6]],"lanterns":[[4,1],[0,7],[3,3],[7,6],[0,0]],"seed":358824,"par":11},
  {"id":29,"band":"B","archetype":"F","blocked":[[2,2],[3,3],[4,4],[5,5],[6,6],[7,7]],"lanterns":[[7,2],[7,6],[6,7]],"seed":582035,"par":5},
  {"id":30,"band":"B","archetype":"A","blocked":[],"lanterns":[[2,5],[7,3],[4,5],[6,0]],"seed":299286,"par":8},
  {"id":31,"band":"C","archetype":"D","blocked":[[3,4],[3,5],[3,6]],"lanterns":[[3,0],[5,3],[3,3],[7,4],[4,2]],"seed":669305,"par":10},
  {"id":32,"band":"C","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[3,5],[1,5],[3,1],[7,4]],"seed":171637,"par":7},
  {"id":33,"band":"C","archetype":"D","blocked":[[4,3],[4,4],[4,5]],"lanterns":[[2,6],[3,4],[1,5],[7,4]],"seed":226259,"par":7},
  {"id":34,"band":"C","archetype":"C","blocked":[[3,0],[3,7],[4,0],[4,7],[5,0],[5,7]],"lanterns":[[1,4],[2,6],[7,1],[2,0]],"seed":359374,"par":9},
  {"id":35,"band":"C","archetype":"D","blocked":[[1,2],[2,2],[3,2]],"lanterns":[[3,7],[0,7],[6,4],[4,4],[1,6]],"seed":722905,"par":10},
  {"id":36,"band":"C","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[2,0],[7,2],[2,2],[0,4],[3,3],[0,1]],"seed":777020,"par":10},
  {"id":37,"band":"C","archetype":"C","blocked":[[0,2],[7,2],[0,3],[7,3],[0,4],[7,4]],"lanterns":[[1,1],[5,3],[3,2],[4,7],[6,1]],"seed":647229,"par":10},
  {"id":38,"band":"C","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[1,2],[0,1],[7,2],[2,7],[1,4],[4,1]],"seed":183838,"par":12},
  {"id":39,"band":"C","archetype":"C","blocked":[[3,0],[3,7],[4,0],[4,7],[5,0],[5,7]],"lanterns":[[0,5],[4,6],[3,1],[7,3],[2,3]],"seed":71066,"par":10},
  {"id":40,"band":"C","archetype":"F","blocked":[[0,0],[1,1],[2,2],[3,3],[4,4]],"lanterns":[[6,2],[3,7],[2,0],[5,3],[5,7],[7,3]],"seed":387981,"par":12},
  {"id":41,"band":"C","archetype":"E","blocked":[[3,5],[4,5],[2,1],[2,2]],"lanterns":[[1,2],[2,0],[0,4],[6,4]],"seed":815335,"par":7},
  {"id":42,"band":"C","archetype":"C","blocked":[[0,2],[7,2],[0,3],[7,3],[0,4],[7,4],[0,5],[7,5]],"lanterns":[[3,5],[4,1],[7,6],[2,2]],"seed":109032,"par":9},
  {"id":43,"band":"C","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[6,5],[4,7],[3,0],[0,1],[1,6]],"seed":46020,"par":11},
  {"id":44,"band":"C","archetype":"C","blocked":[[0,3],[7,3],[0,4],[7,4],[0,5],[7,5]],"lanterns":[[6,7],[0,6],[0,1],[2,5],[4,3]],"seed":290164,"par":10},
  {"id":45,"band":"C","archetype":"D","blocked":[[2,3],[2,4],[2,5],[2,6]],"lanterns":[[1,3],[6,7],[6,0],[4,0],[6,2]],"seed":441278,"par":8},
  {"id":46,"band":"C","archetype":"B","blocked":[[0,0],[0,7],[7,0],[7,7]],"lanterns":[[1,5],[4,3],[4,5],[2,3],[0,1]],"seed":487288,"par":8},
  {"id":47,"band":"C","archetype":"D","blocked":[[3,1],[3,2],[3,3]],"lanterns":[[1,6],[4,1],[0,3],[5,7]],"seed":786097,"par":11},
  {"id":48,"band":"C","archetype":"C","blocked":[[3,0],[3,7],[4,0],[4,7],[5,0],[5,7]],"lanterns":[[0,5],[0,2],[4,5],[7,0],[5,3]],"seed":596815,"par":10},
  {"id":49,"band":"C","archetype":"F","blocked":[[1,6],[2,5],[3,4],[4,3],[5,2]],"lanterns":[[2,6],[1,2],[5,1],[2,4],[2,0]],"seed":73314,"par":8},
  {"id":50,"band":"C","archetype":"A","blocked":[],"lanterns":[[4,3],[0,2],[6,1],[2,7]],"seed":697845,"par":10},
  {"id":51,"band":"C","archetype":"E","blocked":[[6,5],[6,6],[4,1],[5,1],[3,5],[4,5]],"lanterns":[[7,1],[5,2],[1,2],[7,3]],"seed":616042,"par":5},
  {"id":52,"band":"C","archetype":"D","blocked":[[2,3],[3,3],[4,3],[5,3]],"lanterns":[[0,3],[7,3],[3,6],[4,1]],"seed":11009,"par":7,"kit":true},
  {"id":53,"band":"C","archetype":"E","blocked":[[1,4],[2,4],[4,1],[5,1]],"lanterns":[[0,2],[7,6],[3,2],[7,0],[4,6],[7,4]],"seed":89267,"par":10},
  {"id":54,"band":"C","archetype":"E","blocked":[[2,2],[2,3],[5,4],[5,5]],"lanterns":[[2,4],[5,3],[0,7],[7,0]],"seed":11008,"par":10,"kit":true},
  {"id":55,"band":"C","archetype":"F","blocked":[[0,0],[1,1],[2,2],[3,3],[4,4]],"lanterns":[[2,3],[4,3],[7,6],[1,4]],"seed":486580,"par":8},
  {"id":56,"band":"C","archetype":"E","blocked":[[1,5],[1,6],[4,2],[5,2],[3,5],[4,5]],"lanterns":[[2,7],[2,4],[7,4],[2,0],[0,1]],"seed":672914,"par":7},
  {"id":57,"band":"C","archetype":"F","blocked":[[0,7],[1,6],[2,5],[3,4],[4,3]],"lanterns":[[0,2],[0,4],[7,0],[5,3],[5,1]],"seed":35702,"par":9},
  {"id":58,"band":"C","archetype":"E","blocked":[[6,1],[6,2],[4,1],[4,2]],"lanterns":[[5,4],[2,5],[7,1],[2,1],[6,6]],"seed":872069,"par":11},
  {"id":59,"band":"C","archetype":"F","blocked":[[1,1],[2,2],[3,3],[4,4],[5,5],[6,6]],"lanterns":[[1,6],[6,1],[3,5],[5,3]],"seed":11010,"par":13,"kit":true},
  {"id":60,"band":"C","archetype":"F","blocked":[[0,7],[1,6],[2,5],[3,4],[4,3]],"lanterns":[[3,7],[4,6],[6,7],[0,6],[1,5]],"seed":605538,"par":7}
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = LEVELS;
  else root.LANTHORN_LEVELS = LEVELS;
})(typeof globalThis !== "undefined" ? globalThis : this);
